/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package usingobjects;

public class App {
    public static void main(String[] args) {
        UsingObjects.rollDice();
    }
}
