/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

public class App {
    public static void main(String[] args) {
        PASET_ONE.nepalFlag();
        PASET_ONE.andy();
        PASET_ONE.abril();

        PASET_TWO.convertFtoC();
        PASET_TWO.circle();
        PASET_TWO.change();
        PASET_TWO.time();
        PASET_TWO.sumDigits();

        
    }
}