/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

public class App {
    public static void main(String[] args) {
        NepalFlag.run();
        Andy.run();
        Abril.run();
    }
}
