/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        /*
        PASET_ONE.nepalFlag();
        PASET_ONE.andy();
        PASET_ONE.abril();
        *//* 
        PASET_TWO.convertFtoC();
        PASET_TWO.circle();
        PASET_TWO.change();
        PASET_TWO.time();
        PASET_TWO.sumDigits();
        *//* 
        PASET_THREE.run1();
        PASET_THREE.run2();
        PASET_THREE.run3();
        PASET_THREE.run4();
        PASET_THREE.run5();
        PASET_THREE.run6();
        PASET_THREE.run7();
        *//*
        PASET_FOUR.run();
        *//*
        PASET_FIVE.MathMethods.run();
        PASET_FIVE.StringMethodsPart2.run();
        */
        PASET_SIX.run1();
        PASET_SIX.run2();
    }
}